fix: webRTC Class funtions transfer in useContext

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -2,14 +2,6 @@ yarn lint:fix
 yarn prettier:fix
 
 
-#Check tsconfig standards
-# yarn check-types || {
-#     echo '😂🤮❌Failed Type check😂🤮❌
-#     Are you seriously trying to write that? Make the changes required above.'
-#     false;
-# }
-
-
 #Check Prettier standards
 yarn prettier || {
     echo '😂🤮Its Raw - Your styling looks disgusting😂🤮
@@ -25,11 +17,11 @@ yarn lint || {
 #If every thing Passes.... try to run a build
     echo '😂... Alright... Code looks good to me.. Trying to build now. 😂'
 
-#yarn build || {
- #   echo '❌⚒️💡 Better call to your Senior... Because your build failed ❌⚒️💡
- #   Next build Failed: View the erros above to see why.'
- #   false
-#}
+yarn build || {
+    echo '❌⚒️💡 Better call to your Senior... Because your build failed ❌⚒️💡
+    Next build Failed: View the erros above to see why.'
+    false
+}
 
 #If it build we can commit
     echo '✅✅✅ You win this time... I am commiting this now ✅✅✅'
